profile-name: "local"

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://130.162.148.143:3306/dev
    username: dev
    password: chris1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update # or `none` # beta나 실제 서비스에선 none으로 둘 것
    properties:
      hibernate:
        show_sql: true # to System OutDataSourceConfiguration
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul # @CreatedDate 필드의 Time Zone 값 설정